filter:
  excluded_paths:
    - 'tests/'
    - 'vendor/'

build:
  dependencies:
    override:
      - composer update --no-interaction --prefer-dist
  nodes:
    analysis:
      tests:
        override:
          - php-scrutinizer-run --enable-security-analysis
          - command: vendor/bin/phpunit --verbose --coverage-clover=build/coverage.clover
            coverage:
              file: build/coverage.clover
              format: clover
